In [1]:
import pandas as pd

In [2]:
pd.__version__

'3.0.5'

In [18]:
score = [['홍길동', 100, 90, 80],
         ['정약용', 80, 90, 100],
         ['큐리', 10, 20, 30]]
score_df = pd.DataFrame(score, columns=['이름', '국어', '영어', '수학'])
score_df

    이름   국어  영어   수학
0  홍길동  100  90   80
1  정약용   80  90  100
2   큐리   10  20   30

In [19]:
score_df.drop([1], inplace=True)
score_df

    이름   국어  영어  수학
0  홍길동  100  90  80
2   큐리   10  20  30

In [22]:
score_df.reset_index(drop=True)

    이름   국어  영어  수학
0  홍길동  100  90  80
1   큐리   10  20  30