## 1. 파이썬 파일 처리

In [23]:
sample_file = 'data/sample.txt'

In [24]:
# 파일을 open하여 내용 출력
with open(sample_file, mode='rt') as f:
    contents = f.read()
    print(contents)

나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.

In [25]:
# 파일을 open하고 한 줄씩 출력하기
with open(sample_file, mode="r") as f:
    lines = f.readlines()
    print(lines)
    for line in lines:
        print(line, end="")

['나의 속도로\n', '\n', '조금 늦어도 괜찮다.\n', '남들과 같은 길을 갈 필요도 없다.\n', '\n', '오늘 배운 것 하나,\n', '오늘 해결한 문제 하나가\n', '조금씩 나의 실력이 된다.\n', '\n', '결과가 보이지 않는 날에도\n', '나는 앞으로 가고 있다.\n', '\n', '빠르게 가는 것보다\n', '멈추지 않는 것이 중요하다.\n', '\n', '오늘의 작은 한 걸음이\n', '내일의 나를 만든다.\n', '\n', '나는 늦은 것이 아니라\n', '나의 속도로 가고 있다.\n']
나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.

In [26]:
# 파일객체에서 한 줄씩 읽어 오기
# 파일 객체 f를 반복문에서 사용하면 파일을 한 줄씩 읽으며, 각 줄 끝의 \n도 포함해서 가져옵
with open(sample_file, mode="r") as f:
    for line in f:
        print(line)

나의 속도로



조금 늦어도 괜찮다.

남들과 같은 길을 갈 필요도 없다.



오늘 배운 것 하나,

오늘 해결한 문제 하나가

조금씩 나의 실력이 된다.



결과가 보이지 않는 날에도

나는 앞으로 가고 있다.



빠르게 가는 것보다

멈추지 않는 것이 중요하다.



오늘의 작은 한 걸음이

내일의 나를 만든다.



나는 늦은 것이 아니라

나의 속도로 가고 있다.

In [27]:
# 여러 개의 파일 읽기
import glob

files = glob.glob("data/*.txt")
print(files)

for file in files:
    with open(file, mode="r") as f:
        print(f.read())

['data\\hello.txt', 'data\\sample.txt', 'data\\score.txt']
안녕하세요
hello
내용을 추가합니다.
저장하는 문서 이름,  'w' 대신 'a'를 사용합니다.

나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.

90
100
85
95

## 2. 파이썬 문자열 다루기

In [28]:
### 양쪽 공백 제거
b1=" 작은 일에 성실한 사람은      큰일에도 성실하고 "
print(b1)
print(b1.strip())

 작은 일에 성실한 사람은      큰일에도 성실하고
작은 일에 성실한 사람은      큰일에도 성실하고

In [29]:
# 왼쪽 문자, 오른쪽 문자, 양쪽 문자 제거
text="....작은 일에 성실한 사람은, 큰일에도 성실하고...."
print(text)
print(text.lstrip('.'))
print(text.strip('.'))

....작은 일에 성실한 사람은, 큰일에도 성실하고....
작은 일에 성실한 사람은, 큰일에도 성실하고....
작은 일에 성실한 사람은, 큰일에도 성실하고

In [30]:
# ,로 문자열 분리
text="....작은 일에 성실한 사람은, 큰일에도 성실하고...."
print(text.split(","))

['....작은 일에 성실한 사람은', ' 큰일에도 성실하고....']

In [31]:
# .으로 문자열 분리
numbers="1. 2. 3. 4. 5. 6"
print(numbers.split("."))
num_strs = numbers.split(".")
num_list =list(map(int,num_strs))
print(num_list)

['1', ' 2', ' 3', ' 4', ' 5', ' 6']
[1, 2, 3, 4, 5, 6]

## 3. 판다스로 데이터 가져오기

In [32]:
!pip install pandas

Requirement already satisfied: pandas in c:\Users\USER\anaconda3\envs\pydata26\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\USER\anaconda3\envs\pydata26\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\USER\anaconda3\envs\pydata26\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\USER\anaconda3\envs\pydata26\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\Users\USER\anaconda3\envs\pydata26\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [33]:
# 타이타닉 데이터 가져오기
titanic_data = 'https://raw.githubusercontent.com/sehakflower/data/main/titanic.csv'
import pandas as pd
titanic_df = pd.read_csv(titanic_data)
titanic_df

                        PassengerId\tSurvived\tPclass\tName\tSex\tAge\tSibSp\tParch\tTicket\tFare\tCabin\tEmbarked
1\t0\t3\tBraund           Mr. Owen Harris\tmale\t22\t1\t0\tA/5 21171\t7...
2\t1\t1\tCumings          Mrs. John Bradley (Florence Briggs Thayer)\tf...
3\t1\t3\tHeikkinen        Miss. Laina\tfemale\t26\t0\t0\tSTON/O2. 31012...
4\t1\t1\tFutrelle         Mrs. Jacques Heath (Lily May Peel)\tfemale\t3...
5\t0\t3\tAllen            Mr. William Henry\tmale\t35\t0\t0\t373450\t8....
...                                                                    ...
152\t1\t1\tPears          Mrs. Thomas (Edith Wearne)\tfemale\t22\t1\t0\...
153\t0\t3\tMeo            Mr. Alfonzo\tmale\t55.5\t0\t0\tA.5. 11206\t8....
154\t0\t3\tvan Billiard   Mr. Austin Blyler\tmale\t40.5\t0\t2\tA/5. 851...
155\t0\t3\tOlsen          Mr. Ole Martin\tmale\t\t0\t0\tFa 265302\t7.31...
156\t0\t1\tWilliams       Mr. Charles Duane\tmale\t51\t0\t1\tPC 17597\t...

[156 rows x 1 columns]

In [42]:
# 탭을 기존으로 분리하여 읽기
titanic_df = pd.read_csv(titanic_data, sep="\t")
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

# 4. 판다스 데이터 처리

### 4-1. 데이터 구조 및 구성 확인

In [35]:
# 앞부분 확인
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [36]:
# 뒷부분 확인
titanic_df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [37]:
# 데이터 개수/형태 확인
titanic_df.shape

(156, 12)

In [38]:
#데이터의 기본 통계치 보기
titanic_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,156.000000,156.000000,156.000000,126.000000,156.000000,156.000000,156.000000
mean,78.500000,0.346154,2.423077,28.141508,0.615385,0.397436,28.109587
std,45.177428,0.477275,0.795459,14.613880,1.056235,0.870146,39.401047
min,1.000000,0.000000,1.000000,0.830000,0.000000,0.000000,6.750000
25%,39.750000,0.000000,2.000000,19.000000,0.000000,0.000000,8.003150
50%,78.500000,0.000000,3.000000,26.000000,0.000000,0.000000,14.454200
75%,117.250000,1.000000,3.000000,35.000000,1.000000,0.000000,30.371850
max,156.000000,1.000000,3.000000,71.000000,5.000000,5.000000,263.000000

In [39]:
# 데이터 구성 정보 확인하기
titanic_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  156 non-null    int64
 1   Survived     156 non-null    int64
 2   Pclass       156 non-null    int64
 3   Name         156 non-null    str
 4   Sex          156 non-null    str
 5   Age          126 non-null    float64
 6   SibSp        156 non-null    int64
 7   Parch        156 non-null    int64
 8   Ticket       156 non-null    str
 9   Fare         156 non-null    float64
 10  Cabin        31 non-null     str
 11  Embarked     155 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 14.8 KB

In [40]:
titanic_df.survived.value_counts()

AttributeError: 'DataFrame' object has no attribute 'survived'

In [ ]:
titanic_df['age'].value_counts()

age
21.00    8
22.00    6
19.00    6
29.00    6
28.00    5
24.00    5
38.00    4
26.00    4
20.00    4
35.00    3
2.00     3
27.00    3
14.00    3
34.00    3
18.00    3
17.00    3
16.00    3
33.00    3
23.00    3
54.00    2
4.00     2
40.00    2
42.00    2
45.00    2
32.00    2
25.00    2
37.00    2
47.00    2
32.50    2
51.00    2
58.00    1
39.00    1
55.00    1
31.00    1
15.00    1
8.00     1
66.00    1
3.00     1
7.00     1
49.00    1
65.00    1
28.50    1
5.00     1
11.00    1
0.83     1
30.00    1
46.00    1
59.00    1
71.00    1
14.50    1
70.50    1
12.00    1
9.00     1
36.50    1
55.50    1
40.50    1
Name: count, dtype: int64

In [ ]:
# 데이터프레임 복사하기
backup_titanic_df = titanic_df.copy()

In [ ]:
# 열 이름 변경하기 : 모두 소문자로 변경
new_columns = []
for col in titanic_df.columns:
    new_columns.append(col[0].lower() + col[1:])

titanic_df.columns = new_columns
titanic_df.head()

,passengeridassengerid,survivedurvived,pclassclass,nameame,sexex,agege,sibspibsp,parcharch,ticketicket,fareare,cabinabin,embarkedmbarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [45]:
backup_titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C