## 5-1. 그룹별로 요약하여 데이터 확인
* value_counts(), groupby(), pivot_table()

In [5]:
sample_file = 'data/sales_sample.csv'

In [6]:
# 샘플 파일 로딩
import pandas as pd
sample_df = pd.read_csv(sample_file)
sample_df.head()

   지역   상품  판매수량   매출
0  서울  노트북     2  120
1  서울  태블릿     1   80
2  부산  노트북     2  100
3  부산  태블릿     1   70
4  서울  노트북     3  150

In [7]:
# 지역별 판매 기록의 개수
sample_df.지역.value_counts()

지역
서울    7
부산    7
대전    6
Name: count, dtype: int64

In [8]:
# 상품별 판매 기록의 개수와 비율
sample_df.상품.value_counts()

상품
노트북    10
태블릿    10
Name: count, dtype: int64

In [9]:
sample_df.상품.value_counts(normalize=True)

상품
노트북    0.5
태블릿    0.5
Name: proportion, dtype: float64

In [10]:
# 지역과 상품의 조합별 판매 기록 개수
sample_df.value_counts(['지역', '상품'])

지역  상품
서울  노트북    4
부산  태블릿    4
서울  태블릿    3
부산  노트북    3
대전  노트북    3
    태블릿    3
Name: count, dtype: int64

In [11]:
# 지역별 총매출
sample_df.groupby('지역')['매출'].sum()

지역
대전    585
부산    850
서울    850
Name: 매출, dtype: int64

In [12]:
# 상품별 평균 매출
sample_df.groupby('상품')['매출'].mean()

상품
노트북    112.5
태블릿    116.0
Name: 매출, dtype: float64

In [13]:
# 지역별 판매수량의 합계와 매출의 합계
sample_df.groupby('지역')[['판매수량', '매출']].sum()

    판매수량   매출
지역
대전    11  585
부산    13  850
서울    13  850

In [14]:
# 지역별 매출의 건수, 합계, 평균, 최대값
sample_df.groupby('지역')['매출'].agg(['count', 'sum', 'mean', 'max'])

    count  sum        mean  max
지역
대전      6  585   97.500000  135
부산      7  850  121.428571  210
서울      7  850  121.428571  160

In [15]:
# 지역과 상품별 평균 매출
sample_df.pivot_table(
    index = '지역',
    columns= '상품',
    values= '매출',
    aggfunc= 'mean'
)

상품    노트북         태블릿
지역
대전  105.0   90.000000
부산  120.0  122.500000
서울  112.5  133.333333

In [16]:
# 그룹바이로
sample_df.groupby(['지역', '상품'])['매출'].mean()

지역  상품
대전  노트북    105.000000
    태블릿     90.000000
부산  노트북    120.000000
    태블릿    122.500000
서울  노트북    112.500000
    태블릿    133.333333
Name: 매출, dtype: float64

In [17]:
# 지역별·상품별 총매출을 구하고 행과 열의 합계 표시
sample_df.pivot_table(
    index = '지역',
    columns= '상품',
    values= '매출',
    aggfunc= 'sum',
    margins= True
)

상품    노트북   태블릿   All
지역
대전    315   270   585
부산    360   490   850
서울    450   400   850
All  1125  1160  2285

## 5-2. 결측치 처리

In [18]:
sample_df = pd.read_csv('data/sample_data.csv')
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [19]:
# 컬럼별 결측치 갯수 확인
sample_df.isnull()

    Name    Age  Gender   City
0  False  False   False  False
1  False   True   False  False
2  False  False   False   True
3  False  False   False  False
4  False   True   False  False
5  False  False   False  False
6  False  False   False  False

In [20]:
# 컬럼별로 결측치가 있는지의 여부 확인
sample_df.isnull().any()

Name      False
Age        True
Gender    False
City       True
dtype: bool

In [21]:
# 'Age' 컬럼에 결측치가 몇개 있는지 확인
sample_df['Age'].isnull()

0    False
1     True
2    False
3    False
4     True
5    False
6    False
Name: Age, dtype: bool

In [22]:
sample_df['Age'].isnull().sum()

np.int64(2)

In [23]:
# 'Age' 컬럼에 결측치가 있는 행 확인
sample_df[sample_df['Age'].isnull()]

     Name  Age Gender         City
1     Bob  NaN      M  Los Angeles
4  Edward  NaN      M      Houston

In [24]:
# 결측치가 하나라도 있는 행 추출 
sample_df.isnull().any(axis=1)

0    False
1     True
2     True
3    False
4     True
5    False
6    False
dtype: bool

In [25]:
sample_df.isnull().any(axis=1).sum()

np.int64(3)

In [26]:
# 결측치가 하나라도 있는 행 삭제
sample_df.dropna()

    Name   Age Gender      City
0  Alice  24.0      F  New York
3  David  29.0      M   Chicago
5  Alice  24.0      F  New York
6  Susan  32.0      F   Houston

In [27]:
# 'City' 컬럼에 결측치가 있는 행 삭제
sample_df.dropna(subset=['City'])

     Name   Age Gender         City
0   Alice  24.0      F     New York
1     Bob   NaN      M  Los Angeles
3   David  29.0      M      Chicago
4  Edward   NaN      M      Houston
5   Alice  24.0      F     New York
6   Susan  32.0      F      Houston

In [28]:
# 'Age' 컬럼의 결측치를 평균값으로 채우기]
sample_df['Age'] = sample_df['Age'].fillna(sample_df['Age'].mean())
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob  26.2      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward  26.2      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

## 5-3. 중복값 처리하기

In [29]:
# 결측치가 있어서 duplicate으로 추출되지 않을 수 있어서
# 결측치 제거 후 중복 여부 확인


# 중복값인 행 확인
sample_df.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
6    False
dtype: bool

In [30]:
sample_df.duplicated(keep=False).sum()

np.int64(2)

In [31]:
# 중복값인 행 추출
sample_df[sample_df.duplicated(keep=False)]

    Name   Age Gender      City
0  Alice  24.0      F  New York
5  Alice  24.0      F  New York

In [32]:
# 중복값인 행 삭제
sample_df.drop_duplicates()

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob  26.2      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward  26.2      M      Houston
6    Susan  32.0      F      Houston

In [33]:
# 이름, 도시에 중복이 있는지 확인
sample_df[['Name', 'City']].duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
6    False
dtype: bool

In [34]:
# 이름, 도시가 중복인 행 추출
duplicated_df = sample_df[sample_df.duplicated(subset=["Name", "City"], keep=False)]

In [35]:
# 이름, 도시가 중복인 행 삭제
sample_df.drop_duplicates(subset=['Name', 'City'])

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob  26.2      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward  26.2      M      Houston
6    Susan  32.0      F      Houston

## 타이타닉 데이터 실습

In [36]:
# 타이타닉 데이터 가져오기
titanic_data = 'https://raw.githubusercontent.com/sehakflower/data/main/titanic.csv'
titanic_df = pd.read_csv(titanic_data, sep='\t')
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [37]:
titanic_df_copy = titanic_df.copy()

In [38]:
titanic_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  156 non-null    int64
 1   Survived     156 non-null    int64
 2   Pclass       156 non-null    int64
 3   Name         156 non-null    str
 4   Sex          156 non-null    str
 5   Age          126 non-null    float64
 6   SibSp        156 non-null    int64
 7   Parch        156 non-null    int64
 8   Ticket       156 non-null    str
 9   Fare         156 non-null    float64
 10  Cabin        31 non-null     str
 11  Embarked     155 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 14.8 KB

In [39]:
# 컬럼명을 소문자로 변경
titanic_df = titanic_df.rename(columns=str.lower)

In [40]:
# 'age' 컬럼의 결측치 수
titanic_df.age.isnull().sum()

np.int64(30)

In [41]:
# 'age' 컬럼이 결측치인 행
titanic_df[titanic_df['age'].isnull()]

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
29,30,0,3,"Todoroff, Mr. Lalio",male,NaN,0,0,349216,7.8958,NaN,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
32,33,1,3,"Glynn, Miss. Mary Agatha",female,NaN,0,0,335677,7.7500,NaN,Q
36,37,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,2677,7.2292,NaN,C
42,43,0,3,"Kraeff, Mr. Theodor",male,NaN,0,0,349253,7.8958,NaN,C
45,46,0,3,"Rogers, Mr. William John",male,NaN,0,0,S.C./A.4. 23567,8.0500,NaN,S
46,47,0,3,"Lennon, Mr. Denis",male,NaN,1,0,370371,15.5000,NaN,Q
47,48,1,3,"O'Driscoll, Miss. Bridget",female,NaN,0,0,14311,7.7500,NaN,Q
48,49,0,3,"Samaan, Mr. Youssef",male,NaN,2,0,2662,21.6792,NaN,C
55,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S
64,65,0,1,"Stewart, Mr. Albert A",male,NaN,0,0,PC 17605,27.7208,NaN,C
65,66,1,3,"Moubarek, Master. Gerios",male,NaN,1,1,2661,15.2458,NaN,C
76,77,0,3,"Staneff, Mr. Ivan",male,NaN,0,0,349208,7.8958,NaN,S
77,78,0,3,"Moutal, Mr. Rahamin Haim",male,NaN,0,0,374746,8.0500,NaN,S
82,83,1,3,"McDermott, Miss. Brigdet Delia",female,NaN,0,0,330932,7.7875,NaN,Q
87,88,0,3,"Slocovski, Mr. Selman Francis",male,NaN,0,0,SOTON/OQ 392086,8.0500,NaN,S
95,96,0,3,"Shorney, Mr. Charles Joseph",male,NaN,0,0,374910,8.0500,NaN,S
101,102,0,3,"Petroff, Mr. Pastcho (""Pentcho"")",male,NaN,0,0,349215,7.8958,NaN,S
107,108,1,3,"Moss, Mr. Albert Johan",male,NaN,0,0,312991,7.7750,NaN,S
109,110,1,3,"Moran, Miss. Bertha",female,NaN,1,0,371110,24.1500,NaN,Q
121,122,0,3,"Moore, Mr. Leonard Charles",male,NaN,0,0,A4. 54510,8.0500,NaN,S
126,127,0,3,"McMahon, Mr. Martin",male,NaN,0,0,370372,7.7500,NaN,Q
128,129,1,3,"Peter, Miss. Anna",female,NaN,1,1,2668,22.3583,F E69,C
140,141,0,3,"Boulos, Mrs. Joseph (Sultana)",female,NaN,0,2,2678,15.2458,NaN,C
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S

In [42]:
# 'age' 컬럼이 결측치인 사람들의 이름
titanic_df.loc[titanic_df['age'].isnull(), 'name']

5                                    Moran, Mr. James
17                       Williams, Mr. Charles Eugene
19                            Masselmani, Mrs. Fatima
26                            Emir, Mr. Farred Chehab
28                      O'Dwyer, Miss. Ellen "Nellie"
29                                Todoroff, Mr. Lalio
31     Spencer, Mrs. William Augustus (Marie Eugenie)
32                           Glynn, Miss. Mary Agatha
36                                   Mamee, Mr. Hanna
42                                Kraeff, Mr. Theodor
45                           Rogers, Mr. William John
46                                  Lennon, Mr. Denis
47                          O'Driscoll, Miss. Bridget
48                                Samaan, Mr. Youssef
55                                  Woolner, Mr. Hugh
64                              Stewart, Mr. Albert A
65                           Moubarek, Master. Gerios
76                                  Staneff, Mr. Ivan
77                           Moutal, Mr. Rahamin Haim
82                     McDermott, Miss. Brigdet Delia
87                      Slocovski, Mr. Selman Francis
95                        Shorney, Mr. Charles Joseph
101                  Petroff, Mr. Pastcho ("Pentcho")
107                            Moss, Mr. Albert Johan
109                               Moran, Miss. Bertha
121                        Moore, Mr. Leonard Charles
126                               McMahon, Mr. Martin
128                                 Peter, Miss. Anna
140                     Boulos, Mrs. Joseph (Sultana)
154                             Olsen, Mr. Ole Martin
Name: name, dtype: str

In [43]:
titanic_df.age.mean()

np.float64(28.141507936507935)

In [44]:
# 'age'컬럼의 결측치를 age의 평균으로 채우기
titanic_df.age.fillna(titanic_df.age.mean())

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
151    22.000000
152    55.500000
153    40.500000
154    28.141508
155    51.000000
Name: age, Length: 156, dtype: float64

In [45]:
#19번 행의 데이터 확인
titanic_df.loc[19]

passengerid                         20
survived                             1
pclass                               3
name           Masselmani, Mrs. Fatima
sex                             female
age                                NaN
sibsp                                0
parch                                0
ticket                            2649
fare                             7.225
cabin                              NaN
embarked                             C
Name: 19, dtype: object

In [46]:
titanic_df.age.isnull().sum()

np.int64(30)

In [47]:
# 'cabin'의 결측치를 'N'으로 채우고, 알파벳 한자리로 변경하기
# 'cabin' 컬럼의 결측치 확인
titanic_df.cabin.isnull().sum()

np.int64(125)

In [48]:
# 'cabin'의 결측치를 'N'으로 채우기
titanic_df.cabin = titanic_df.cabin.fillna('N')
titanic_df.loc[4]

passengerid                           5
survived                              0
pclass                                3
name           Allen, Mr. William Henry
sex                                male
age                                35.0
sibsp                                 0
parch                                 0
ticket                           373450
fare                               8.05
cabin                                 N
embarked                              S
Name: 4, dtype: object

In [49]:
titanic_df.cabin.isnull().sum()

np.int64(0)

In [50]:
# 'cabin' 컬럼의 값 확인
titanic_df.cabin.value_counts()

cabin
N              125
C123             2
C23 C25 C27      2
D26              2
C85              1
E46              1
G6               1
C103             1
D56              1
A6               1
B78              1
D33              1
B30              1
C52              1
B28              1
C83              1
F33              1
F G73            1
E31              1
A5               1
D10 D12          1
C110             1
B58 B60          1
E101             1
F E69            1
D47              1
B86              1
F2               1
C2               1
Name: count, dtype: int64

In [51]:
# 객실의 알파벳값만 남겨 놓기
titanic_df.cabin.apply(lambda x : x[0])

0      N
1      C
2      N
3      C
4      N
      ..
151    C
152    N
153    N
154    N
155    N
Name: cabin, Length: 156, dtype: str

In [52]:
titanic_df.cabin.value_counts()

cabin
N              125
C123             2
C23 C25 C27      2
D26              2
C85              1
E46              1
G6               1
C103             1
D56              1
A6               1
B78              1
D33              1
B30              1
C52              1
B28              1
C83              1
F33              1
F G73            1
E31              1
A5               1
D10 D12          1
C110             1
B58 B60          1
E101             1
F E69            1
D47              1
B86              1
F2               1
C2               1
Name: count, dtype: int64

In [55]:
# 'embarked' 컬럼의 결측치 삭제
titanic_df = titanic_df.dropna(subset=['embarked'])
titanic_df

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,N,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,N,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,N,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,N,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,N,C

In [54]:
titanic_df.info()

<class 'pandas.DataFrame'>
Index: 155 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   passengerid  155 non-null    int64
 1   survived     155 non-null    int64
 2   pclass       155 non-null    int64
 3   name         155 non-null    str
 4   sex          155 non-null    str
 5   age          125 non-null    float64
 6   sibsp        155 non-null    int64
 7   parch        155 non-null    int64
 8   ticket       155 non-null    str
 9   fare         155 non-null    float64
 10  cabin        155 non-null    str
 11  embarked     155 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 15.7 KB