## 1. 파이썬 파일 처리

In [1]:
sample_file = './data/sample.txt'

In [2]:
# 파일을 open하여 전체 내용을 읽어서 출력
with open(sample_file, mode='r') as f:
    content = f.read()
    print(content)
print("----- 끝 -----")

나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.

----- 끝 -----

In [3]:
# 파일을 open하고 한 줄씩 읽어서 출력하기 : readlines(), readline()
with open(sample_file, mode= 'r') as f:
    lines = f.readlines()
    for line in lines:
        print(line, end='')

print("----- 끝 -----")

나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.
----- 끝 -----

In [111]:
# 파일객체에서 한 줄씩 읽어 오기
# 파일 객체 f를 반복문에서 사용하면 파일을 한 줄씩 읽으며,
# 각 줄 끝의 \n도 포함해서 가져옵
sample_file = 'data/sample.txt'

with open(sample_file, mode='r') as f:
    for line in f:
        print(line, end='')


print("----- 끝 -----")

나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.
----- 끝 -----

In [36]:
# 여러 개의 파일 읽기 (모든 txt 파일을 읽어서 출력하기)
import glob
txt_file_pattern = './data/sales_sample.csv'
files = glob.glob(txt_file_pattern)
print(files)
for file in files:
    with open(file, mode='r') as f:
        content = f.read()
        print(content)
    
print("----- 끝 -----")

['./data/sales_sample.csv']
지역,상품,판매수량,매출
서울,노트북,2,120
서울,태블릿,1,80
부산,노트북,2,100
부산,태블릿,1,70
서울,노트북,3,150
부산,노트북,1,110
대전,노트북,2,130
대전,태블릿,2,90
서울,태블릿,2,160
부산,태블릿,3,210
대전,노트북,1,65
대전,태블릿,1,45
서울,노트북,1,60
부산,노트북,3,150
대전,노트북,2,120
서울,태블릿,2,160
부산,태블릿,1,70
대전,태블릿,3,135
서울,노트북,2,120
부산,태블릿,2,140

----- 끝 -----

## 2. 파이썬 문자열 다루기

In [15]:
# 양쪽 공백 제거
b1=" 작은 일에 성실한 사람은      큰일에도 성실하고 "
b1.strip()

'작은 일에 성실한 사람은      큰일에도 성실하고'

In [18]:
# 왼쪽 문자, 오른쪽 문자, 양쪽 문자 제거
text="....작은 일에 성실한 사람은, 큰일에도 성실하고...."
text.strip('.')

'작은 일에 성실한 사람은, 큰일에도 성실하고'

In [23]:
# ,로 문자열 분리
text="....작은 일에 성실한 사람은, 큰일에도 성실하고...."
text.strip('.').split(',')

['작은 일에 성실한 사람은', ' 큰일에도 성실하고']

In [18]:
# .으로 문자열 분리
numbers="1. 2. 3. 4. 5. 6"
numbers.split('.')

['1', ' 2', ' 3', ' 4', ' 5', ' 6']

## 3. 판다스로 데이터 가져오기

In [181]:
# 판다스 설치
!pip install pandas

Requirement already satisfied: pandas in C:\Users\USER\anaconda3\envs\pydata26\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\USER\anaconda3\envs\pydata26\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\USER\anaconda3\envs\pydata26\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\USER\anaconda3\envs\pydata26\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\USER\anaconda3\envs\pydata26\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [182]:
# 연습용 sample_data.csv 로딩하기
sample_file = './data/sample_data.csv'

import pandas as pd
sample_df = pd.read_csv(sample_file)
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [183]:
sample_df.to_csv('./data/sample_data_copy.csv')

In [184]:
# 타이타닉 데이터 가져오기
titanic_data = 'https://raw.githubusercontent.com/sehakflower/data/main/titanic.csv'

In [10]:
# 데이터를 읽으면서 탭을 기준으로 분리하여 데이터 프레임으로 만들기
t_df = pd.read_csv(titanic_data, sep='\t')
t_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# 4. 판다스 데이터 처리

### 4-1. 데이터 구조 및 구성 확인

In [35]:
# 앞부분 확인
t_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [36]:
# 뒷부분 확인
t_df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [39]:
# 데이터 개수/형태 확인
t_df.shape

(156, 12)

In [40]:
#데이터의 기본 통계치 보기
t_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,156.000000,156.000000,156.000000,126.000000,156.000000,156.000000,156.000000
mean,78.500000,0.346154,2.423077,28.141508,0.615385,0.397436,28.109587
std,45.177428,0.477275,0.795459,14.613880,1.056235,0.870146,39.401047
min,1.000000,0.000000,1.000000,0.830000,0.000000,0.000000,6.750000
25%,39.750000,0.000000,2.000000,19.000000,0.000000,0.000000,8.003150
50%,78.500000,0.000000,3.000000,26.000000,0.000000,0.000000,14.454200
75%,117.250000,1.000000,3.000000,35.000000,1.000000,0.000000,30.371850
max,156.000000,1.000000,3.000000,71.000000,5.000000,5.000000,263.000000

In [41]:
# 데이터 구성 정보 확인하기
t_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  156 non-null    int64
 1   Survived     156 non-null    int64
 2   Pclass       156 non-null    int64
 3   Name         156 non-null    str
 4   Sex          156 non-null    str
 5   Age          126 non-null    float64
 6   SibSp        156 non-null    int64
 7   Parch        156 non-null    int64
 8   Ticket       156 non-null    str
 9   Fare         156 non-null    float64
 10  Cabin        31 non-null     str
 11  Embarked     155 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 14.8 KB

In [57]:
# 타이타닉 데이터 구조 및 구성 확인하기
t_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  156 non-null    int64
 1   Survived     156 non-null    int64
 2   Pclass       156 non-null    int64
 3   Name         156 non-null    str
 4   Sex          156 non-null    str
 5   Age          126 non-null    float64
 6   SibSp        156 non-null    int64
 7   Parch        156 non-null    int64
 8   Ticket       156 non-null    str
 9   Fare         156 non-null    float64
 10  Cabin        31 non-null     str
 11  Embarked     155 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 14.8 KB

### 4-2. 컬럼명과 인덱스 정리

In [11]:
# 데이터프레임 복사하기(deep copy)
sample_backup_df = sample_df.copy()
sample_backup_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [28]:
sample_df =sample_df.rename(columns=str.capitalize)
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [29]:
# 컬럼명의 첫글자는 소문자로, 나머지는 대문자로 수정
sample_df = sample_df.rename(columns=lambda x: x[0].lower() + x[1:].upper())
sample_df

      nAME   aGE gENDER         cITY
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [24]:
# 열 이름 변경하기 : 모두 소문자로 변경
# new_cols = []
# for col in sample_df.columns:
#    new_cols.append(col.lower())

sample_df.columns = [col.lower() for col in sample_df.columns]
sample_df

      name   age gender         city
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [31]:
# index 확인
t_df.index

RangeIndex(start=0, stop=156, step=1)

In [33]:
t_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [34]:
# 행 데이터 삭제하기
drop_index = [2, 4, 152, 154]
# t_df.drop([], axis=0, inplace=True)
t_df = t_df.drop(drop_index, axis=0)
t_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...
149,150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
150,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [42]:
# index를 0부터 순서대로 assign 되도록 reset하기
t_df = t_df.reset_index(drop=True)
t_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
3,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...
147,150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
148,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
149,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
150,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
151,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [55]:
t_df = t_df.rename(columns=lambda x: x.lower())

In [62]:
# 컬럼 PassengerId를 index로 설정하기
t_df = t_df.set_index('passengerid')
t_df

,index,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
passengerid,,,,,,,,,,,,
1,0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
4,2,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,3,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,4,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...
150,147,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
151,148,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
152,149,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
154,150,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
156,151,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [60]:
# index를 컬럼으로 만들고, index를 RangeIndex로 reset하기
t_df= t_df.reset_index(drop=False)
t_df

,index,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
3,3,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
4,4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,147,150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
148,148,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
149,149,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
150,150,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
151,151,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

### 4-3. 데이터 정렬

In [63]:
# 'age' 기준으로 정렬
t_df.sort_values(by='age')

,index,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
passengerid,,,,,,,,,,,,
79,76,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
8,5,0,3,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,21.0750,NaN,S
17,14,0,3,"Rice, Master. Eugene",male,2.00,4,1,382652,29.1250,NaN,Q
120,117,0,3,"Andersson, Miss. Ellis Anna Maria",female,2.00,4,2,347082,31.2750,NaN,S
44,41,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
110,107,1,3,"Moran, Miss. Bertha",female,NaN,1,0,371110,24.1500,NaN,Q
122,119,0,3,"Moore, Mr. Leonard Charles",male,NaN,0,0,A4. 54510,8.0500,NaN,S
127,124,0,3,"McMahon, Mr. Martin",male,NaN,0,0,370372,7.7500,NaN,Q
129,126,1,3,"Peter, Miss. Anna",female,NaN,1,1,2668,22.3583,F E69,C
141,138,0,3,"Boulos, Mrs. Joseph (Sultana)",female,NaN,0,2,2678,15.2458,NaN,C

In [64]:
# 'age' 기준으로 내림차순으로 정렬
t_df.sort_values(by='age', ascending=False)

,index,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
passengerid,,,,,,,,,,,,
97,94,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
117,114,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
34,31,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
55,52,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
95,92,0,3,"Coxon, Mr. Daniel",male,59.0,0,0,364500,7.2500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
110,107,1,3,"Moran, Miss. Bertha",female,NaN,1,0,371110,24.1500,NaN,Q
122,119,0,3,"Moore, Mr. Leonard Charles",male,NaN,0,0,A4. 54510,8.0500,NaN,S
127,124,0,3,"McMahon, Mr. Martin",male,NaN,0,0,370372,7.7500,NaN,Q
129,126,1,3,"Peter, Miss. Anna",female,NaN,1,1,2668,22.3583,F E69,C
141,138,0,3,"Boulos, Mrs. Joseph (Sultana)",female,NaN,0,2,2678,15.2458,NaN,C

In [71]:
# 'age', 'pclass'를 기준으로 정렬
t_df.sort_values(by=['pclass', 'age'], ascending=False)

# pclass 는 오름차순, age는 내림차순으로 정렬
t_df.sort_values(by=['pclass', 'age'], ascending=[True,False])

,index,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
passengerid,,,,,,,,,,,,
97,94,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
55,52,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
12,9,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
7,4,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
125,122,0,1,"White, Mr. Percival Wayland",male,54.0,0,1,35281,77.2875,D26,S
...,...,...,...,...,...,...,...,...,...,...,...,...
110,107,1,3,"Moran, Miss. Bertha",female,NaN,1,0,371110,24.1500,NaN,Q
122,119,0,3,"Moore, Mr. Leonard Charles",male,NaN,0,0,A4. 54510,8.0500,NaN,S
127,124,0,3,"McMahon, Mr. Martin",male,NaN,0,0,370372,7.7500,NaN,Q
129,126,1,3,"Peter, Miss. Anna",female,NaN,1,1,2668,22.3583,F E69,C
141,138,0,3,"Boulos, Mrs. Joseph (Sultana)",female,NaN,0,2,2678,15.2458,NaN,C

In [75]:
# index를 기준으로 정렬
t_df = t_df.sort_index()
t_df

,index,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
passengerid,,,,,,,,,,,,
1,0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
4,2,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,3,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,4,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...
150,147,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
151,148,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
152,149,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
154,150,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
156,151,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

### 4-4. 데이터 접근/추출
* 범위 지정 : 직접 지정, 인덱서 이용
* 조건 지정

In [78]:
score_dict={'이름': ['정약용', '이순신', '이율곡', '홍길동'],
            '국어' : [70, 100, 90, 85],
            '영어' : [80, 80, 95, 100],
            '수학' : [100, 70, 90, 90]}
score_df = pd.DataFrame(score_dict)
score_df

    이름   국어   영어   수학
0  정약용   70   80  100
1  이순신  100   80   70
2  이율곡   90   95   90
3  홍길동   85  100   90

In [79]:
# 행 지정 -> 슬라이싱
score_df[2:3]

    이름  국어  영어  수학
2  이율곡  90  95  90

In [82]:
# 열 접근
score_df['이름']
score_df.이름

0    정약용
1    이순신
2    이율곡
3    홍길동
Name: 이름, dtype: str

In [83]:
score_df.이름

0    정약용
1    이순신
2    이율곡
3    홍길동
Name: 이름, dtype: str

In [84]:
score_df[['이름', '국어']]

    이름   국어
0  정약용   70
1  이순신  100
2  이율곡   90
3  홍길동   85

In [87]:
# 특정 (행,열)의 데이터 접근
score_df[1:2][['이름', '국어']]

    이름   국어
1  이순신  100

In [88]:
score_df

    이름   국어   영어   수학
0  정약용   70   80  100
1  이순신  100   80   70
2  이율곡   90   95   90
3  홍길동   85  100   90

In [89]:
# 인덱서 이용 : 레이블(이름) 인덱서
# 행 접근
score_df.loc[1]

이름    이순신
국어    100
영어     80
수학     70
Name: 1, dtype: object

In [92]:
# 열 접근
score_df.loc[:,['이름', '국어']]

    이름   국어
0  정약용   70
1  이순신  100
2  이율곡   90
3  홍길동   85

In [95]:
# (행,열) 접근
score_df.loc[:1,'국어':'영어']

    국어  영어
0   70  80
1  100  80

In [98]:
# 인덱서 이용 : 위치(숫자) 인덱서
# 행 접근
score_df.iloc[:1]

    이름  국어  영어   수학
0  정약용  70  80  100

In [99]:
# 열 접근
score_df.iloc[:,1:3]

    국어   영어
0   70   80
1  100   80
2   90   95
3   85  100

In [100]:
# (행,열) 접근
score_df.iloc[:2, 1:3]

    국어  영어
0   70  80
1  100  80

In [101]:
# 조건 지정 추출 : Boolean Indexing
# 직접 지정 방식으로 행 추출
score_df[score_df.수학 >= 90]

    이름  국어   영어   수학
0  정약용  70   80  100
2  이율곡  90   95   90
3  홍길동  85  100   90

In [102]:
score_df[(score_df. 국어 >= 90) & (score_df.수학 >= 90)]

    이름  국어  영어  수학
2  이율곡  90  95  90

In [103]:
score_df[score_df.이름.isin(['정약용', '이순신'])]

    이름   국어  영어   수학
0  정약용   70  80  100
1  이순신  100  80   70

In [104]:
# 인덱서 방식으로 행 추출
score_df.loc[score_df.수학 >= 90]

    이름  국어   영어   수학
0  정약용  70   80  100
2  이율곡  90   95   90
3  홍길동  85  100   90

In [106]:
# (행,열) 데이터 추출
score_df.loc[score_df.수학 >= 90, ['이름', '수학']]

    이름   수학
0  정약용  100
2  이율곡   90
3  홍길동   90

In [108]:
# 열 데이터에 조건 지정
score_df.loc[:,score_df.columns != '영어']

    이름   국어   수학
0  정약용   70  100
1  이순신  100   70
2  이율곡   90   90
3  홍길동   85   90

In [109]:
score_df.loc[:,score_df.dtypes == 'int']

    국어   영어   수학
0   70   80  100
1  100   80   70
2   90   95   90
3   85  100   90

## 실습 과제. 데이터 가져오기

In [116]:
#지정 범위의 행에서 데이터 가져오기
t_df[0:5] # head()와 동일한 결과
t_df[0:1] # 첫 행만 가져오기
t_df[::3] # 3개씩 건너서 출력
t_df[::-1] # 역순으로 출력

,index,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
passengerid,,,,,,,,,,,,
156,151,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C
154,150,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
152,149,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
151,148,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
150,147,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
7,4,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
6,3,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
4,2,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
2,1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
1,0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S

In [118]:
# 단순 인덱스로 범위 지정해 데이터 가져오기
t_df[:3]

,index,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
passengerid,,,,,,,,,,,,
1,0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
4,2,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [122]:
# 지정 범위의 열에서 데이터 가져오기
len(t_df.columns)

# 첫 번쨰 열을 1차원 배열을 Series 객체로 추출
t_df[t_df.columns[0]]

passengerid
1        0
2        1
4        2
6        3
7        4
      ...
150    147
151    148
152    149
154    150
156    151
Name: index, Length: 152, dtype: int64

In [ ]:
# 마지막 열을 1차원 배열의 Series 객체로 추출
t_df[t_df.columns[11]]
#t_df[t_df.columns[-1]]

passengerid
1      S
2      C
4      S
6      Q
7      S
      ..
150    S
151    S
152    S
154    S
156    C
Name: embarked, Length: 152, dtype: str

In [125]:
# 열 이름으로 데이터 가져오기
age=t_df['age']
print(type(age))

<class 'pandas.Series'>

In [127]:
# 'age' 열을 1차원 배열인 Series 객체로 추출
t_df['age']
t_df.age

passengerid
1      22.0
2      38.0
4      35.0
6       NaN
7      54.0
       ...
150    42.0
151    51.0
152    22.0
154    40.5
156    51.0
Name: age, Length: 152, dtype: float64

In [146]:
t_df

,index,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
passengerid,,,,,,,,,,,,
1,0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
4,2,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,3,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,4,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...
150,147,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
151,148,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
152,149,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
154,150,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
156,151,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [147]:
# 열 이름과 위치를 이용해 데이터 가져오기
#print(t_df[t_df.columns[0]][0])
#print(t_df['age'][0])
#print(t_df[t_df.columns[0]][2])
#print(t_df[t_df[-1]][0])
type(t_df[t_df.columns[0]][1])

numpy.int64

In [156]:
# 열 이름과 위치 이용해 [시작값: 종료값: 증가값]
t_df[t_df.columns[0]][2:6]
t_df[t_df.columns[0]][:-1]
t_df[t_df.columns[0]][::3]
t_df[t_df.columns[0]][-1:]
t_df[t_df.columns[0]][::-1]

passengerid
156    151
154    150
152    149
151    148
150    147
      ...
7        4
6        3
4        2
2        1
1        0
Name: index, Length: 152, dtype: int64

In [159]:
# 여러 개의 열 이름을 리스트 형태로 만들어 특정 열을 가져올 수 있고 열 순서를 이용해 데이터 추출
t_df[['pclass', 'name', 'sex']]
t_df[[t_df.columns[2], t_df.columns[3],t_df.columns[4]]]

             pclass                                               name     sex
passengerid
1                 3                            Braund, Mr. Owen Harris    male
2                 1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female
4                 1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
6                 3                                   Moran, Mr. James    male
7                 1                            McCarthy, Mr. Timothy J    male
...             ...                                                ...     ...
150               2                  Byles, Rev. Thomas Roussel Davids    male
151               2                         Bateman, Rev. Robert James    male
152               1                  Pears, Mrs. Thomas (Edith Wearne)  female
154               3                    van Billiard, Mr. Austin Blyler    male
156               1                        Williams, Mr. Charles Duane    male

[152 rows x 3 columns]

In [163]:
# 위에 걸 슬라이싱 형태로
t_df[[t_df.columns[2], t_df.columns[3], t_df.columns[4]]][2:15:3]

             pclass                                          name     sex
passengerid
4                 1  Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
8                 3                Palsson, Master. Gosta Leonard    male
11                3               Sandstrom, Miss. Marguerite Rut  female
14                3                   Andersson, Mr. Anders Johan    male
17                3                          Rice, Master. Eugene    male

In [169]:
# 데이터 프레임에서 사용할 수 있는 인덱싱
#print(t_df[t_df.columns[0]][0]) 
print(t_df[t_df.columns[0]][2])
# print(t_df[t_df.columns[0]][-1]) # 실행 시 오류.. 왜? 키에러
type(t_df[t_df.columns[0]][1])

1

numpy.int64

In [194]:
import pandas as pd

t_df1 = pd.read_csv('https://raw.githubusercontent.com/sehakflower/data/main/titanic.csv')

In [230]:
t_df1 = pd.read_csv(titanic_data, sep='\t')
t_df1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [231]:
# 인덱스를 다시 0, 1, 2숫자로 리셋
t_df1 = t_df1.reset_index(drop=True)

In [205]:
# 인덱스이름 기준으로 데이터 가져오기 : loc 속성
t_df1.loc[0]
t_df1.loc[0:5]
t_df1.loc[0:10:2]

   PassengerId\tSurvived\tPclass\tName\tSex\tAge\tSibSp\tParch\tTicket\tFare\tCabin\tEmbarked
0    Mr. Owen Harris\tmale\t22\t1\t0\tA/5 21171\t7...
2    Miss. Laina\tfemale\t26\t0\t0\tSTON/O2. 31012...
4    Mr. William Henry\tmale\t35\t0\t0\t373450\t8....
6    Mr. Timothy J\tmale\t54\t0\t0\t17463\t51.8625...
8    Mrs. Oscar W (Elisabeth Vilhelmina Berg)\tfem...
10   Miss. Marguerite Rut\tfemale\t4\t1\t1\tPP 954...

In [232]:
t_df1.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [ ]:
t_df1.loc[:, 'Age']

      Age     Sex
0    22.0    male
1    38.0  female
2    26.0  female
3    35.0  female
4    35.0    male
..    ...     ...
151  22.0  female
152  55.5    male
153  40.5    male
154   NaN    male
155  51.0    male

[156 rows x 2 columns]

In [234]:
t_df1.loc[:,['Age', 'Sex']]

      Age     Sex
0    22.0    male
1    38.0  female
2    26.0  female
3    35.0  female
4    35.0    male
..    ...     ...
151  22.0  female
152  55.5    male
153  40.5    male
154   NaN    male
155  51.0    male

[156 rows x 2 columns]

In [235]:
t_df1.loc[3:7,['Age', 'Sex']]

    Age     Sex
3  35.0  female
4  35.0    male
5   NaN    male
6  54.0    male
7   2.0    male

In [237]:
t_df1.loc[2:5, 'Survived':'Age']

,Survived,Pclass,Name,Sex,Age
2,1,3,"Heikkinen, Miss. Laina",female,26.0
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0
4,0,3,"Allen, Mr. William Henry",male,35.0
5,0,3,"Moran, Mr. James",male,NaN

In [244]:
# 인덱스 순서를 기준으로 데이터 가져오기 : iloc 속성
t_df1.iloc[0]
t_df1.iloc[0:5]
t_df1.iloc[0:10:3]
t_df1.iloc[:,[0,2]]
t_df1.iloc[1:5, [0,2]]
t_df1.iloc[1:5, 1:4]

   Survived  Pclass                                               Name
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2         1       3                             Heikkinen, Miss. Laina
3         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4         0       3                           Allen, Mr. William Henry

## 4-5. 그룹별로 요약하여 데이터 확인
* value_counts()
* groupby()
* pivot_table()

In [ ]:
sample_file = 'data/sales_sample.csv'

In [ ]:
# 샘플 파일 로딩

In [ ]:
# 지역별 판매 기록의 개수

In [ ]:
# 상품별 판매 기록의 개수와 비율

In [ ]:
# 지역과 상품의 조합별 판매 기록 개수

In [ ]:
# 지역별 총매출

In [ ]:
# 상품별 평균 매출

In [ ]:
# 지역별 판매수량의 합계와 매출의 합계

In [ ]:
# 지역과 상품별 평균 매출

In [ ]:
# 지역별·상품별 총매출을 구하고 행과 열의 합계 표시