# 5-1. 결측치 처리

In [1]:
# 판다스 설치
!pip install pandas

Requirement already satisfied: pandas in C:\Users\USER\anaconda3\envs\pydata26\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\USER\anaconda3\envs\pydata26\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\USER\anaconda3\envs\pydata26\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\USER\anaconda3\envs\pydata26\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\USER\anaconda3\envs\pydata26\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
# 연습용 sample_data.csv 로딩하기
sample_file = 'data/sample_data.csv'

import pandas as pd
sample_df = pd.read_csv(sample_file)
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [3]:
sample_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      str
 1   Age     5 non-null      float64
 2   Gender  7 non-null      str
 3   City    6 non-null      str
dtypes: float64(1), str(3)
memory usage: 356.0 bytes

In [11]:
# isna
sample_df.isna()
# 컬럼 지정 가능
# sample_df['Age'].isna()

    Name    Age  Gender   City
0  False  False   False  False
1  False   True   False  False
2  False  False   False   True
3  False  False   False  False
4  False   True   False  False
5  False  False   False  False
6  False  False   False  False

In [12]:
# isnull
sample_df.isnull().sum()

Name      0
Age       2
Gender    0
City      1
dtype: int64

In [15]:
# 결측치가 있는 데이터 확인
# 'Age'컬럼에 결측치가 있는지와 결측치 데이터 확인
print(sample_df['Age'].isna().sum())
sample_df[sample_df['Age'].isna()]

2

     Name  Age Gender         City
1     Bob  NaN      M  Los Angeles
4  Edward  NaN      M      Houston

In [17]:
# 어떤 컬럼이든 결측치가 있는 데이터의 갯수, 데이터 확인
na_df = sample_df[sample_df.isna().any(axis=1)]
print(len(na_df))

3

In [18]:
sample_df[sample_df.isna().any(axis=1)]

      Name   Age Gender         City
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
4   Edward   NaN      M      Houston

In [ ]:
# 결측치가 있는 데이터 삭제 : dropna
# City에 결측치가 있는 경우 데이터 삭제
sample_df.dropna(subset='City')

     Name   Age Gender         City
0   Alice  24.0      F     New York
1     Bob   NaN      M  Los Angeles
3   David  29.0      M      Chicago
4  Edward   NaN      M      Houston
5   Alice  24.0      F     New York
6   Susan  32.0      F      Houston

In [22]:
sample_df = sample_df.dropna(subset='City')
sample_df

     Name   Age Gender         City
0   Alice  24.0      F     New York
1     Bob   NaN      M  Los Angeles
3   David  29.0      M      Chicago
4  Edward   NaN      M      Houston
5   Alice  24.0      F     New York
6   Susan  32.0      F      Houston

In [30]:
# Age 결측치는 Age의 평균값으로 채우기
age_avg = sample_df['Age'].mean()
sample_df['Age'] = sample_df['Age'].fillna(sample_df['Age'].mean())
sample_df

     Name    Age Gender         City
0   Alice  24.00      F     New York
1     Bob  27.25      M  Los Angeles
3   David  29.00      M      Chicago
4  Edward  27.25      M      Houston
5   Alice  24.00      F     New York
6   Susan  32.00      F      Houston

## 5-2. 중복치 처리

In [31]:
# 중복값 확인
sample_df.duplicated()

0    False
1    False
3    False
4    False
5     True
6    False
dtype: bool

In [32]:
sample_df.duplicated().sum()

np.int64(1)

In [33]:
sample_df[sample_df.duplicated()]

    Name   Age Gender      City
5  Alice  24.0      F  New York

In [35]:
# 중복값 삭제
sample_df = sample_df.drop_duplicates()
sample_df

     Name    Age Gender         City
0   Alice  24.00      F     New York
1     Bob  27.25      M  Los Angeles
3   David  29.00      M      Chicago
4  Edward  27.25      M      Houston
6   Susan  32.00      F      Houston